version: 2.1

parameters:
  prod-branch:
    type: string
    default: "react-static"
  qa-branch:
    type: string
    default: "react-static"

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  jq: circleci/jq@2.2.0

commands:

  setup-awscli:
    description: "Setup awscli and jq"
    steps:
      - aws-cli/setup
      - jq/install:
          version: jq-1.6

  get-dist-config:
    description: "Request distribution config from Cloudfront"
    parameters:
      dist-id:
        type: string
      filename:
        type: string
    steps:
      - run:
          name: "Request distribution config from Cloudfront"
          command: |
            aws cloudfront get-distribution-config --id <<parameters.dist-id>> > <<parameters.filename>>

jobs:

  generate-build:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - run: node --version && yarn --version
      - checkout
      - run:
          name: "Create timestamp file"
          command: date --utc +%Y%m%d_%H%M%S > circleci_timestamp
#      - restore_cache:
#          keys:
#            - node-modules-v1_{{ checksum "yarn.lock" }}
#      - run: yarn install
#      - save_cache:
#          key: node-modules-v1_{{ checksum "yarn.lock" }}
#          paths:
#            - node_modules
#      - run: yarn build
#      - run:
#          name: "Create build tarball"
#          command: tar czf build.tar.gz build
      - persist_to_workspace:
          root: .
          paths:
            - circleci_timestamp
#            - build
#            - build.tar.gz

  get-dist-configs:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup-awscli
      - get-dist-config:
          dist-id: $AWS_CF_PRELIVE
          filename: circleci_prelive_dist_config.json
      - get-dist-config:
          dist-id: $AWS_CF_LIVE
          filename: circleci_live_dist_config.json
      - persist_to_workspace:
          root: .
          paths:
            - circleci_live_dist_config.json
            - circleci_prelive_dist_config.json




  another-job:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - attach_workspace:
          at: ./
      - run: cat circleci_timestamp
      - run: cat circleci_live_dist_config.json
      - run: cat circleci_prelive_dist_config.json

workflows:

#  qa_build_push_deploy:
#    jobs:
#      - build-and-push:
#          repo-name: $AWS_ECR_QA_REPO_NAME
#          filters:
#            branches:
#              only: <<pipeline.parameters.qa-branch>>
#      - simple-deploy-service:
#          repo-name: $AWS_ECR_QA_REPO_NAME
#          service-name: $AWS_ECS_QA_SERVICE
#          container-name: $AWS_TASK_DEF_QA_CONTAINER
#          family: $AWS_TASK_DEF_QA_FAMILY
#          requires:
#            - build-and-push
#          filters:
#            branches:
#              only: <<pipeline.parameters.qa-branch>>

  do-the-thing:
    jobs:
      - generate-build:
          filters:
            branches:
              only: <<pipeline.parameters.prod-branch>>
      - get-dist-configs:
          requires:
            - generate-build
          filters:
            branches:
              only: <<pipeline.parameters.prod-branch>>
      - another-job:
          requires:
            - get-distribution-configs
          filters:
            branches:
              only: <<pipeline.parameters.prod-branch>>
#      - selective-deploy-service:
#          requires:
#            - build-and-push
#          filters:
#            branches:
#              only: <<pipeline.parameters.prod-branch>>
#      - switch-to-live-now:
#          type: approval
#          requires:
#            - selective-deploy-service
#      - toggle-target-groups:
#          requires:
#            - switch-to-live-now
#          filters:
#            branches:
#              only: <<pipeline.parameters.prod-branch>>
