version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  jq: circleci/jq@2.2.0

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - aws-cli/setup
      - jq/install:
          version: jq-1.6
      - run:
          name: "Get latest number tag and increment it"
          command: |
            tag1=$(aws ecr describe-images --repository-name ${AWS_ECR_REPO_NAME} --image-ids imageTag=latest | jq -r '.imageDetails[0].imageTags | map(select(. != "latest"))[0]')
            tag2=$((tag1 + 1))
            echo New image tag will be ${tag2}
            echo "export NEW_IMAGE_TAG=${tag2}" >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          remote-docker-layer-caching: true
          repo: nes
          tag: ${NEW_IMAGE_TAG},latest
  test-vars:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - aws-cli/setup
      - jq/install:
          version: jq-1.6

workflows:
  build_push_deploy:
    jobs:
#      - test-vars:
#          filters:
#            branches:
#              only: kotlin-docker
      - build-and-push:
          filters:
            branches:
              only: kotlin-docker
      - wait:
          type: approval
          requires:
            - build-and-push
      - aws-ecs/deploy-service-update:
          cluster-name: ${AWS_ECS_CLUSTER_NAME}
          service-name: ${AWS_ECS_SERVICE_NAME}
          family: ${AWS_ECS_TASK_DEF_FAMILY}
          skip-task-definition-registration: true
          force-new-deployment: true
          requires:
            - wait
          filters:
            branches:
              only: kotlin-docker
