version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  jq: circleci/jq@2.2.0

commands:
  setup-awscli:
    description: "Setup awscli and jq"
    steps:
      - aws-cli/setup
      - jq/install:
          version: jq-1.6
  get-latest-image-tag:
    description: "Get number tag of image currently marked as 'latest' in repo"
    parameters:
      repo-name:
        type: string
    steps:
      - run:
          name: "Get latest number tag from repo"
          command: |
            res=$(aws ecr describe-images --repository-name <<parameters.repo-name>> --image-ids imageTag=latest || echo empty)
            if [[ "$res" == "empty" ]]; then
              tag=0
            else
              tag=$(echo $res | jq -r '.imageDetails[0].imageTags | map(select(. != "latest"))[0]')
            fi

            echo Latest image tag is ${tag}
            echo "export CONF_LATEST_IMG_TAG=${tag}" >> $BASH_ENV
  increment-latest-tag:
    description: "Increment CONF_LATEST_IMG_TAG env var"
    steps:
      - run:
          name: "Increment latest image tag"
          command: |
            tag=$((CONF_LATEST_IMG_TAG + 1))
            echo New image tag will be ${tag}
            echo "export CONF_NEW_IMG_TAG=${tag}" >> $BASH_ENV
  get-deploy-variables:
    description: "Generate variables for selective deploy"
    steps:
      - run:
          name: "Generate deploy variables"
          command: |
            tgroup_old=$(aws elbv2 describe-rules --rule-arns ${AWS_RULE_ARN_PRELIVE} | jq -r '.Rules[0].Actions[0].TargetGroupArn')

            if [[ "$tgroup_old" == "$AWS_TGROUP_ARN_1" ]]; then
              echo "export CONF_ECS_SERVICE=${AWS_ECS_SERVICE_1}" >> $BASH_ENV
              echo "export CONF_LIVE_TGROUP=${AWS_TGROUP_ARN_1}" >> $BASH_ENV
              echo "export CONF_PRELIVE_TGROUP=${AWS_TGROUP_ARN_2}" >> $BASH_ENV
              tgroup_old_num=1
            elif [[ "$tgroup_old" == "$AWS_TGROUP_ARN_2" ]]; then
              echo "export CONF_ECS_SERVICE=${AWS_ECS_SERVICE_2}" >> $BASH_ENV
              echo "export CONF_LIVE_TGROUP=${AWS_TGROUP_ARN_2}" >> $BASH_ENV
              echo "export CONF_PRELIVE_TGROUP=${AWS_TGROUP_ARN_1}" >> $BASH_ENV
              tgroup_old_num=2
            else
              >&2 echo "Pre-live ALB listener rule is currently not associated with either target groups"
              exit 2
            fi

            echo Deploy to service designation ${tgroup_old_num}

jobs:
  build-and-push:
    parameters:
      repo-name:
        type: string
    docker:
      - image: cimg/python:3.9
    steps:
      - setup-awscli
      - get-latest-image-tag:
          repo-name: <<parameters.repo-name>>
      - increment-latest-tag
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          remote-docker-layer-caching: true
          repo: $AWS_ECR_REPO_NAME
          tag: ${CONF_NEW_IMG_TAG},latest
  selective-deploy-service:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup-awscli
      - get-latest-image-tag:
          repo-name: $AWS_ECR_REPO_NAME
      - get-deploy-variables
      - aws-ecs/update-service:
          cluster-name: $AWS_ECS_CLUSTER_NAME
          service-name: $CONF_ECS_SERVICE
          family: $AWS_TASK_DEF_FAMILY
          container-image-name-updates: 'container=${AWS_TASK_DEF_CONTAINER},tag=${CONF_LATEST_IMG_TAG}'
          task-definition-tags: 'key=CreatedBy,value=CircleCI'
          verify-revision-is-deployed: true
  toggle-target-groups:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup-awscli
      - get-deploy-variables
      - run:
          name: "Toggle target group associations"
          command: |
            aws elbv2 modify-rule --rule-arn ${AWS_RULE_ARN_PRELIVE} --actions Type=forward,TargetGroupArn=${AWS_TGROUP_ARN_BRIDGE}
            aws elbv2 modify-rule --rule-arn ${AWS_RULE_ARN_LIVE} --actions Type=forward,TargetGroupArn=${CONF_LIVE_TGROUP}
            aws elbv2 modify-rule --rule-arn ${AWS_RULE_ARN_PRELIVE} --actions Type=forward,TargetGroupArn=${CONF_PRELIVE_TGROUP}
  test-job:
    docker:
      - image: cimg/python:3.9
    steps:
      - run: echo nothing

workflows:
#  qa_build_push_deploy:
#    jobs:
#      - build-and-push:
#          repo-name: $AWS_ECR_QA_REPO_NAME
#          filters:
#            branches:
#              only: kotlin-docker
  prod_build_push_deploy:
    jobs:
#      - test-job:
#          filters:
#            branches:
#              only: kotlin-docker
      - build-and-push:
          repo-name: $AWS_ECR_REPO_NAME
          filters:
            branches:
              only: kotlin-docker
      - pause:
          type: approval
          requires:
            - build-and-push
      - selective-deploy-service:
          requires:
            #- build-and-push
            - pause
          filters:
            branches:
              only: kotlin-docker
      - switch-to-live-now:
          type: approval
          requires:
            - selective-deploy-service
      - toggle-target-groups:
          requires:
            - switch-to-live-now
          filters:
            branches:
              only: kotlin-docker
