version: 2.1

parameters:
  prod-branch:
    type: string
    default: "react-static"
  qa-branch:
    type: string
    default: "react-static"

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  jq: circleci/jq@2.2.0

commands:

  setup-awscli:
    description: "Setup awscli and jq"
    steps:
      - aws-cli/setup
      - jq/install:
          version: jq-1.6

jobs:

  generate-build:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - node-modules-v1_{{ checksum "yarn.lock" }}
#      - run: yarn install
#      - save_cache:
#          key: node-modules-v1_{{ checksum "yarn.lock" }}
#          paths:
#            - node_modules
      - run: mkdir test_files
      - run: echo 'the quick brown fox' > test_files/one
      - run: date --utc +%Y%m%d_%H%M%S > timestamp
      - persist_to_workspace:
          root: .
          paths:
            - test_files
            - timestamp

  another-job:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - attach_workspace:
          at: ./
      - run: cat timestamp && cat test_files/one

workflows:

#  qa_build_push_deploy:
#    jobs:
#      - build-and-push:
#          repo-name: $AWS_ECR_QA_REPO_NAME
#          filters:
#            branches:
#              only: <<pipeline.parameters.qa-branch>>
#      - simple-deploy-service:
#          repo-name: $AWS_ECR_QA_REPO_NAME
#          service-name: $AWS_ECS_QA_SERVICE
#          container-name: $AWS_TASK_DEF_QA_CONTAINER
#          family: $AWS_TASK_DEF_QA_FAMILY
#          requires:
#            - build-and-push
#          filters:
#            branches:
#              only: <<pipeline.parameters.qa-branch>>

  do-the-thing:
    jobs:
      - generate-build:
          filters:
            branches:
              only: <<pipeline.parameters.prod-branch>>
      - another-job:
          requires:
            - generate-build
          filters:
            branches:
              only: <<pipeline.parameters.prod-branch>>
#      - selective-deploy-service:
#          requires:
#            - build-and-push
#          filters:
#            branches:
#              only: <<pipeline.parameters.prod-branch>>
#      - switch-to-live-now:
#          type: approval
#          requires:
#            - selective-deploy-service
#      - toggle-target-groups:
#          requires:
#            - switch-to-live-now
#          filters:
#            branches:
#              only: <<pipeline.parameters.prod-branch>>
