version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  jq: circleci/jq@2.2.0

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - aws-cli/setup
      # do aws stuff here
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          remote-docker-layer-caching: true
          repo: nes
          tag: ${CIRCLE_BUILD_NUM},latest
  test-vars:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - aws-cli/setup
      - jq/install:
          version: jq-1.6
      - run:
          name: "Get latest number tag and increment it"
          command: |
            aws ecr describe-images --repository-name ${AWS_ECR_REPO_NAME} --images-ids imageTag=latest | jq -r '.imageDetails[0]'
      - run:
          name: "Save an env var"
          command: echo 'export LATEST_TAG=3' >> $BASH_ENV
      - run:
          name: "Load an env var"
          command: echo Latest tag is ${LATEST_TAG}
      # test success

workflows:
  build_push_deploy:
    jobs:
      - test-vars:
          filters:
            branches:
              only: kotlin-docker
#      - build-and-push:
#          filters:
#            branches:
#              only: kotlin-docker
#      - wait:
#          type: approval
#          requires:
#            - build-and-push
#      - aws-ecs/deploy-service-update:
#          cluster-name: nes-prod
#          service-name: test
#          force-new-deployment: true
#          family: nes-test
#          skip-task-definition-registration: true
#          requires:
#            - wait
#          filters:
#            branches:
#              only: kotlin-docker
