version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  build_push_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: nes
          tag: ${CIRCLE_BUILD_NUM},latest
          filters:
            branches:
              only: kotlin-docker
      - aws-ecs/deploy-service-update:
          cluster-name: nes-prod
          service-name: test
          force-new-deployment: true
          family: nes-test
          skip-task-definition-registration: true
          type: approval
          requires:
            - aws-ecr/build-and-push-image
