version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  jq: circleci/jq@2.2.0

commands:
  aws-setup:
    description: "Install awscli and jq"
    steps:
      - aws-cli/setup
      - jq/install:
          version: jq-1.6
  get-latest-image-tag:
    description: "Get the number tag of the image currently marked as latest"
    steps:
      - run: |
          tag=$(aws ecr describe-images --repository-name ${AWS_ECR_REPO_NAME} --image-ids imageTag=latest | jq -r '.imageDetails[0].imageTags | map(select(. != "latest"))[0]')
          echo Latest image tag is ${tag}
          echo "export LATEST_IMAGE_TAG=${tag}" >> $BASH_ENV

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - aws-setup
      - get-latest-image-tag
      - run:
          name: "Increment latest image tag"
          command: |
            tag=$((LATEST_IMAGE_TAG + 1))
            echo New image tag will be ${tag}
            echo "export NEW_IMAGE_TAG=${tag}" >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          remote-docker-layer-caching: true
          repo: nes
          tag: ${NEW_IMAGE_TAG},latest
  deploy-service:
    docker:
      - image: cimg/python:3.9
    steps:
      - aws-setup
      - get-latest-image-tag
      - aws-ecs/update-service:
          cluster-name: ${AWS_ECS_CLUSTER_NAME}
          service-name: ${AWS_ECS_SERVICE_1}
          family: ${AWS_TASK_DEF_FAMILY}
          container-image-name-updates: 'container=${AWS_TASK_DEF_CONTAINER},tag=${LATEST_IMAGE_TAG}'
          task-definition-tags: 'key=CreatedBy,value=CircleCI'
          verify-revision-is-deployed: true

  test-job:
    docker:
      - image: cimg/python:3.9
    steps:
      - aws-setup
      - run:
          name: "Get designation for old app version"
          command: |
            tgroup_old=$(aws elbv2 describe-rules --rule-arns ${AWS_RULE_ARN_OLD} | jq -r '.Rules[0].Actions[0].TargetGroupArn')
            echo Old app is associated with target group ${tgroup_old}

            if [[ "$tgroup_old" == "$AWS_TGROUP_ARN_1" ]]; then
              echo "export DESIGNATION_OLD=1" >> $BASH_ENV
            elif [[ "$tgroup_old" == "$AWS_TGROUP_ARN_2" ]]; then
              echo "export DESIGNATION_OLD=2" >> $BASH_ENV
            else
              >&2 echo "None-live ALB is currently not associated with either target groups"
            fi

            echo App will be deployed to service designation ${DESIGNATION_OLD}

workflows:
  build_push_deploy:
    jobs:
      - test-job:
          filters:
            branches:
              only: kotlin-docker
#      - build-and-push:
#          filters:
#            branches:
#              only: kotlin-docker
#      - for-approval:
#          type: approval
#          requires:
#            - build-and-push
#      - deploy-service:
#          requires:
#            - for-approval
#          filters:
#            branches:
#              only: kotlin-docker
